USE [master]
GO

/****** Object:  Database [TelRehber]    Script Date: 3.05.2019 18:44:40 ******/
CREATE DATABASE [TelRehber]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TelRehber', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\TelRehber.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TelRehber_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\TelRehber_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TelRehber].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TelRehber] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TelRehber] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TelRehber] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TelRehber] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TelRehber] SET ARITHABORT OFF 
GO

ALTER DATABASE [TelRehber] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TelRehber] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TelRehber] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TelRehber] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TelRehber] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TelRehber] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TelRehber] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TelRehber] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TelRehber] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TelRehber] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TelRehber] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TelRehber] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TelRehber] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TelRehber] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TelRehber] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TelRehber] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TelRehber] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TelRehber] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TelRehber] SET  MULTI_USER 
GO

ALTER DATABASE [TelRehber] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TelRehber] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TelRehber] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TelRehber] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TelRehber] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TelRehber] SET QUERY_STORE = OFF
GO

ALTER DATABASE [TelRehber] SET  READ_WRITE 
GO


