USE TelRehber

CREATE TABLE	Tbl_Kisiler
(
ID INT IDENTITY(1,1) NOT NULL,
AD VARCHAR(25) NOT NULL,
SOYAD	VARCHAR(25) NOT NULL,
CEP_TEL VARCHAR(10) NOT NULL,
IS_TEL VARCHAR(10) NOT NULL,
EMAIL	VARCHAR(30) NOT NULL,
ADRES VARCHAR(MAX) NOT NULL,
)
